### ISSUE TITLE
Why image is in png format?

### ISSUE THREAD

**Issue by BrandonHanx** [postBG/CosMo.pytorch#1]
https://github.com/postBG/CosMo.pytorch/blob/768b7b8bdb2b8b1812ca04e7de852cd1803ca929/data/fashionIQ.py#L24-L25

Hi, @postBG . Thanks for your great work.

I guess the original images in FashionIQ dataset is in JPG format. While your code is reading images as PNG and thus leads to an error.

Do you have any pre-processing?

**Comment by numpee** [comment]
Hi, @BrandonHanx, thanks for pointing this out. 

I just checked the dataset link, and the images are indeed in `.jpg` format. For some reason, the images on our servers are in `.png`. 
We did not  preprocess the images, but may have changed the extension while moving files around. I will update the code.

**Comment by BrandonHanx** [comment]
Thanks for your quick reply. This issue is solved for me.
