### ISSUE TITLE
LSTM hidden size

### ISSUE THREAD

**Issue by haoyudong-97** [postBG/CosMo.pytorch#10]
In text_encoedrs/lstm.py, the hidden size of LSTM is defined as:
`lstm_hidden_size = kwargs.get('lstm_hidden_size', 512)`

But in text_encoders/__init__.py, the desired lstm hidden size (from config) is not used.

Can you check at this? Thanks.

**Comment by numpee** [comment]
Hi,
As you mentioned, it seems like we used 512 as the LSTM hidden size. This was a mistake on our part.
You can add the 'lstm_hidden_size' in `text_encoders/init.py` if you'd like to change the LSTM hidden size.
Thanks for pointing this out :)

**Comment by numpee** [comment]
I have added two commits to fix this.

**Comment by haoyudong-97** [comment]
Thanks for the reply!
This is a mirror bug indeed, but I find that when the lstm hidden size increases, the performance actually drops.
Particularly, I tested on the dress subsection and the result was:

Size: 512     R@10:  ~0.24
Size: 1024   R@10:  ~0.23
Size: 2048   R@10:  ~0.19

This is kinda counter-intuitive, and I'm wondering if you have any insights on this.
