### ISSUE TITLE
About FasionIQ

### ISSUE THREAD

**Issue by Wangld5** [postBG/CosMo.pytorch#11]
Hi， 
I am very interested in this task.
However,  I try to download the dress data of FasionIQ dataset but found that about 905 image URLs are missing. I finally get 18182 dress image data. I hope to know whether you get a complete dataset and how many images are included in the dataset.
What's more, can you send FashionIQ to my Gmali：wangliangdao5@gmail.com.
Thanks.

**Comment by weihao20** [comment]
> Wangld5

你好，你得到完整的数据集了吗？能否通过云盘分享一下数据集呢，非常感谢！

**Comment by numpee** [comment]
@Wangld5 Please check the updated README: https://github.com/postBG/CosMo.pytorch#arrows_counterclockwise-update-dec-8th-2021
