### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by Wangld5** [postBG/CosMo.pytorch#12]
![image](https://user-images.githubusercontent.com/30035015/133423974-6652befd-681f-415f-a1f7-6143ff22ed92.png)
I test the model in dress dataset, and get the result above. The results do not match the paper and I run it following the command you write. Do you know why ?

**Comment by numpee** [comment]
Hi,
Please refer to the "Notes on Evaluation" part of the README: https://github.com/postBG/CosMo.pytorch#warning-notes-on-evaluation 
Also another user pointed out that some papers concatenate all three training subsets, then evaluate on each subset separately. Doing so will actually lead to better performances than what we reported in our paper.

**Comment by Wangld5** [comment]
Thanks, I will try to uncomment the code presented in fashionIQ.py.
