### ISSUE TITLE
Problems about Fashion200k dataset

### ISSUE THREAD

**Issue by JWargrave** [postBG/CosMo.pytorch#15]
Hi, there.

Thank you for the great work!

According to [fashion200k repo](https://github.com/xthan/fashion-200k#dataset), there are two versions of Fashion200k pictures, namely cropped detected images and original images, which one do you use in your implementation?

**Comment by numpee** [comment]
IIRC we use the same implementation as [TIRG](https://github.com/google/tirg/blob/master/datasets.py#L203) for Fashion200K. I believe this is the cropped images in `women.tar.gz`

**Comment by JWargrave** [comment]
OK, thanks.
