### ISSUE TITLE
Could you share the Shoes dataset?

### ISSUE THREAD

**Issue by KevinHooah** [postBG/CosMo.pytorch#17]
Hi,

Thank you for the great work! I found the the original shoes dataset's link is broken, could you share the dataset? Thank you very much.

**Comment by numpee** [comment]
Hi,

Since we are not the creators of the dataset, we do not own the right to distribute it either. I think your best bet is to contact the dataset owners. Sorry :(

**Comment by KevinHooah** [comment]
I see, thank you!
