### ISSUE TITLE
Different results from provided notebook.

### ISSUE THREAD

**Issue by BrandonHanx** [postBG/CosMo.pytorch#2]
Hi, @postBG . Thanks for your great work.

I am preparing vocab according to the instructions in README. However, I received different output results from `jupyter_files/how_to_create_fashion_iq_vocab.ipynb`. 

My third code block's result is:
```
is solid black with no sleeves and is black with straps
B005X4PL1G
```
And the result of sixth is:
`2957`

I guess you intended to load test split to build vocab while the val split is loaded. But I am not sure. Plase give me some hints.

**Comment by numpee** [comment]
@BrandonHanx Thanks for pointing this out as well. 
It seems like we changed the dataset code a bit after generating the vocab, so you won't get the correct vocab with that.
Let me look into this today, and I'll try to get back to you tomorrow :) 
Sorry for the trouble

**Comment by BrandonHanx** [comment]
Hi @numpee ,

It is fine. No need to apologize. Really appreciate this clean and modularized codebase!

**Comment by numpee** [comment]
Hey @BrandonHanx,
We have added our vocab file to `jupyter_files/fashion_iq_vocab.pkl` for your reference.
We have also updated the jupyter file to output the correct vocab file. 😄

**Comment by BrandonHanx** [comment]
Many thanks. This issue is solved.
