### ISSUE TITLE
Concatenate two captions?

### ISSUE THREAD

**Issue by BrandonHanx** [postBG/CosMo.pytorch#4]
Hi, @numpee 

I also found a little different experimental setting between CosMo and other methods.

As shown in official [FashionIQ evaluation codebase](https://github.com/XiaoxiaoGuo/fashion-iq/blob/7a21dc34fb480c007778295236a8986c2f9739e4/start_kit/data_loader.py#L51-L59): the two captions of each triplet pair are concatenated into one sentence. 

Following this setting, many other methods concatenate two captions while VAL doesn't.

I guess you don't concatenate two captions in order to make a fair comparison with VAL.

However, I guess you may receive higher performance with following this setting.

**Comment by numpee** [comment]
Hi,
We actually do concatenate the two captions, but use both orders for concatenating.
For example, you could have `text1 + and + text2` and `text2 + and + text1`.

**Comment by BrandonHanx** [comment]
Ok. Thanks for your reply. This issue is solved for me.
