### ISSUE TITLE
About other two datasets Shoes and Fashion200K

### ISSUE THREAD

**Issue by Wangld5** [postBG/CosMo.pytorch#6]
Hi, @numpee.
Could you please release the data processing method of the other two datasets ? I want to know to train the model on Shoes and Fashion200K. Thank you.

**Comment by numpee** [comment]
HI @Wangld5,
We use the same data augmentation scheme for all three datasets. You can find the transformation functions in [transforms/image_transforms.py](https://github.com/postBG/CosMo.pytorch/blob/main/transforms/image_transforms.py).

For Fashion200K, we use the same data processing method as TIRG, [here](https://github.com/google/tirg/blob/master/datasets.py#L203). Basically, a search is conducted for two images with similar descriptions that only differ by 1 word. Then, the modifier text would be: "Change A to B", where A and B are the two different descriptions.

**Comment by Wangld5** [comment]
Thanks for your explanation. I also want to know whether your data processing method differs from [VAL](https://github.com/yanbeic/VAL/tree/master/datasets). Because I discover that they have released all the three datasets and their data processing methods on github.

**Comment by postBG** [comment]
Hi, you can refer to the VAL code because we followed the same protocol. 
We actually referred to the code as well.
Thanks!
