### ISSUE TITLE
Actual differences between FashionIQ evaluation method and VAL evaluation method

### ISSUE THREAD

**Issue by ABaldrati** [postBG/CosMo.pytorch#7]
Hi!
In the README file is pointed out that the evaluation method reported in the paper is slightly different from evaluation method of the original FashionIQ dataset (in order to match the method used by VAL).

However, I can't quite figure out which are the actual differences between the two methods.
Can someone explain them to me in detail?
Thanks, Alberto

**Comment by BrandonHanx** [comment]
As mentioned in their paper:

> We follow the evaluation method of VAL [9], where the evaluation split is defined by the union of reference and target images. Thus, compared to the original evaluation split, there are fewer test images, which leads to slightly higher performance than the original version.

In short, normal evaluation's gallery contains: ref imgs + target imgs + some other imgs while VAL's gallery only contains ref imgs + target imgs.

**Comment by ABaldrati** [comment]
Great!
Thank you very much for your prompt reply!
